/**
 * @file myrobot_specific_interface.h
 */

#ifndef INCLUDE_ROS_CONTROL_EXERCISE_MYROBOT_SPECIFIC_INTERFACE_H
#define INCLUDE_ROS_CONTROL_EXERCISE_MYROBOT_SPECIFIC_INTERFACE_H


#endif /* ifndef INCLUDE_ROS_CONTROL_EXERCISE_MYROBOT_SPECIFIC_INTERFACE_H */
